### ISSUE TITLE
Crashes when trying to record in 8K.

### ISSUE THREAD

**Issue by ElPaan** [matcool/TrashBot#40]
how to fix this? Please help.

https://user-images.githubusercontent.com/79516881/190730206-30c0f469-7ef4-4a28-9928-eeb0dae1bfdd.mp4

**Comment by ElPaan** [comment]
![image](https://user-images.githubusercontent.com/79516881/190799017-4acb4a45-14f5-45a5-9d58-fd1e20de1497.png)

**Comment by TechStudent10** [comment]
I have a few hunches;

I think the problem is that ReplayBot is used inside of GD. GD only has 2GB of RAM available to it (unless you are using the 4GB patch). 8K takes up a ton of resources and since GD doesn't have access to that much memory, it simply crashes.

This could also be that your GPU and/or CPU aren't capable of 8K recording.
